name: Auto Create Pull Request

on:
  push:
    branches:
      - dev

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      - name: Update author information
        run: echo ${{ env.GIT COMMIT_AUTHOR_NAME}}> AUTHOR
      - name: Raise PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "auto-pr-branch"
          base: main
          title: "deno for auto pr"
          committer: ${{ env.GIT COMMIT_AUTHOR_NAME}} <${{ env.GIT COMMIT_AUTHOR_EMAIL }}"> 
          author: ${{ env.GIT COMMIT_AUTHOR_NAME}} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"> 
          body: This is to show automatic PR creation
          token: ${{ secrets.MY_PULL_REQ_TOKEN }}
          delete-branch: true 

    
