name: Run Unit Tests and Merge to Main

on:
  pull_request:
    branches:
      - test

jobs:
  unit-tests-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests.py

      - name: Setup Git for PR and Merge
        if: success() # This ensures the step runs only if previous steps succeed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create Pull Request to main
        if: success() # Continues only if tests pass
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          source_branch: "test"
          pr_title: "Automated PR to merge test into main"
          pr_body: "This is an automated pull request to merge changes from test into main after tests passed."
          pr_label: "automerge"
          github_token: ${{ secrets.MY_PULL_REQ_TOKEN }}
      
      - name: Auto-merge PR
        if: steps.create_pr.outputs.pull_request_number
        uses: pascalgn/automerge-action@v0.14.2
        with:
          mergeMethod: merge
          token: ${{ secrets.MY_PULL_REQ_TOKEN }}
          pullRequest: ${{ steps.create_pr.outputs.pull_request_number }}
